setwd('E:/excelr data/assignments/multi linear regression/fitted')
library(readr)
startups <- read.csv('E:/excelr data/assignments/multi linear regression/50_Startups.csv')
View(startups)
startups_new <- as.data.frame(scale(startups[,-4]))
View(startups_new)
pairs(startups_new)
cor(startups_new)
attach(startups_new)
#Model 1 (without removing any influencial parametres and transformation)
startups.model <- lm(Profit~.,data=startups_new)
summary(startups.model)
#Model 2 (with logirthemic transformation to the dependent variable)
startups.model_trans <- lm(log(Profit)~.,data=startups_new)
summary(startups.model_trans)
#Model 3(after applying logirthemic transformation to all the variables)
startups.model_trans_new <- lm(Profit~(log(R.D.Spend)+log(Administration)+log(Marketing.Spend)),data=startups_new)
summary(startups.model_trans_new)
#Model 4 (after removing the influenced parametres)
library(car)
vif(startups.model)
avPlots(startups.model)
influencePlot(startups.model)
startups.changed <- lm(Profit~.-Administration,data=startups_new[-c(46,47,49,50),])
summary(startups.changed)
#Model 5(after removing the influenced parametres and applying logirthemic transformation)
startups.changed_transformed <- lm(log(Profit)~.-Administration,data=startups_new[-c(46,47,49,50),])
summary(startups.changed_transformed)
prediction <- predict(startups.changed,level=0.95)
prediction
confint(startups.changed,level=0.95)
pred1 <-as.data.frame(predict(startups.changed,interval='prediction'))
pred1
final_fit <- cbind(startups_new[-c(46,47,49,50),],pred1)
write.csv(final_fit,file="50_startups_fit")

