library(arules)
library(arulesViz)
book <- read.csv('E:/excelr data/assignments/Assosciation rules/book (1).csv')
View(book)
book_trans <- as(as.matrix(book),"transactions")
inspect(book_trans)
book_rules <- apriori(book_trans,parameter = list(support=0.1,confidence=0.75))
class(book_rules)
inspect(book_rules)
plot(book_rules)
book_rules_df <- DATAFRAME(book_rules)
View(book_rules_df)
write.csv(book_rules_df,file='book_rules')
grocery <- read.csv('E:/excelr data/assignments/Assosciation rules/groceries.csv')
View(grocery)
grocery_trans <- as(grocery,"transactions")
grocery_rules <- apriori(grocery_trans,parameter = list(support=0.1,confidence=0.75))
inspect(grocery_rules)
movies <- read.csv('E:/excelr data/assignments/Assosciation rules/my_movies.csv')
movies <- movies[,6:15]
movies_trans <- as(as.matrix(movies),'transactions')
movies_rules <- apriori(movies_trans,parameter = list(support=0.2,confidence=0.75))
inspect(movies_rules)
movies_df <- DATAFRAME(movies_rules)
write.csv(movies_df,file='movies')
getwd()
