#Model 1 ( Applying transformation to both the independent and dependent variable)
library(ggplot2)
library(readr)
delivery <- read.csv('E:/excelr data/assignments/simple regression//delivery_time.csv')
View(delivery)
attach(delivery)
plot(log(Delivery.Time),log(Sorting.Time))
cor(log(Delivery.Time),log(Sorting.Time))
delivery_model <- lm(log(Sorting.Time)~log(Delivery.Time))
summary(delivery_model)
confint(delivery_model,level = 0.95)
pred1 <- predict(delivery_model)
delivery_model_dataset <- as.data.frame(predict(delivery_model,interval = 'predict'))
delivery_model_final <- cbind(delivery,delivery_model_dataset)
write.csv(delivery_model_final,file='delivery_fit')
ggplot(data=delivery,aes(x=log(Delivery.Time),y=log(Sorting.Time)))+
         geom_point(color='blue')+geom_line(color='red',data=delivery,aes(x=log(Delivery.Time),y=pred1))

#Model 2 ( without Applying transformation)

library(ggplot2)
library(readr)
delivery <- read.csv('E:/excelr data/assignments/simple regression//delivery_time.csv')
View(delivery)
attach(delivery)
plot((Delivery.Time),Sorting.Time)
cor((Delivery.Time),Sorting.Time)
delivery_model <- lm(Sorting.Time~(Delivery.Time))
summary(delivery_model)
confint(delivery_model,level = 0.95)
pred1 <- predict(delivery_model)
delivery_model_dataset <- as.data.frame(predict(delivery_model,interval = 'predict'))
delivery_model_final <- cbind(delivery,delivery_model_dataset)
write.csv(delivery_model_final,file='delivery_fit_notr')
ggplot(data=delivery,aes(x=(Delivery.Time),y=Sorting.Time))+
  geom_point(color='blue')+geom_line(color='red',data=delivery,aes(x=Delivery.Time,y=pred1))


#Model 3 ( Applying transformation on dependent Variable)

library(ggplot2)
library(readr)
delivery <- read.csv('E:/excelr data/assignments/simple regression//delivery_time.csv')
View(delivery)
attach(delivery)
plot(Delivery.Time,sqrt(Sorting.Time))
cor(Delivery.Time,sqrt(Sorting.Time))
delivery_model <- lm(sqrt(Sorting.Time)~Delivery.Time)
summary(delivery_model)
confint(delivery_model,level = 0.95)
pred1 <- predict(delivery_model)
delivery_model_dataset <- as.data.frame(predict(delivery_model,interval = 'predict'))
delivery_model_final <- cbind(delivery,delivery_model_dataset)
write.csv(delivery_model_final,file='delivery_fit_squred')
ggplot(data=delivery,aes(x=Delivery.Time,y=sqrt(Sorting.Time)))+
  geom_point(color='blue')+geom_line(color='red',data=delivery,aes(x=Delivery.Time,y=pred1))
