library(readr)
library(readxl)
EastWestAirlines <- read_excel('E:/excelr data/assignments/clustering/EastWestAirlines.xlsx',1)
View(EastWestAirlines)
EastWestAirlines_norm <- scale(EastWestAirlines[,-1])
d <- dist(EastWestAirlines_norm,method = 'euclidean')
fit <- hclust(d,method="complete")
plot(fit)
plot(fit,hang=-1)
membreship <- as.data.frame(as.matrix(cutree(fit,k=5)))
cluster <- rect.hclust(fit,k=5,border = 'red')
fit_final<- cbind(EastWestAirlines,membreship)
library(dplyr)
fit_final_new <-  rename(fit_final,membreship=V1)
fit_final_new <- fit_final_new[,c(1,13,2:12)]
write.csv(fit_final_new,file="EastWestAirlines_clustered")
getwd()