#Model 1(with no transformation)
library(ggplot2)
library(readr)
emp_data <- read.csv('E:/excelr data/assignments/simple regression/emp_data.csv')
View(emp_data)
attach(emp_data)
cor(Salary_hike,Churn_out_rate)
emp_data_model <- lm(Churn_out_rate~Salary_hike)
summary(emp_data_model)
pred <- predict(emp_data_model)
ggplot(data = emp_data, aes(x = Salary_hike, y = Churn_out_rate)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = emp_data, aes(x=Salary_hike, y=pred))
confint(emp_data_model,level=0.95)
emp_data_dataset <- as.data.frame(predict(emp_data_model,interval='predict'))
emp_data_final <- cbind(emp_data,emp_data_dataset)
write.csv(emp_data_final,file='emp_data_fit')
#Model 2(with Square root transformation on independent Variable)
library(ggplot2)
library(readr)
emp_data <- read.csv('E:/excelr data/assignments/simple regression/emp_data.csv')
View(emp_data)
attach(emp_data)
cor(sqrt(Salary_hike),Churn_out_rate)
plot(sqrt(Salary_hike),Churn_out_rate)
emp_data_model <- lm(Churn_out_rate~sqrt(Salary_hike))
summary(emp_data_model)
pred <- predict(emp_data_model)
ggplot(data = emp_data, aes(x = sqrt(Salary_hike), y =Churn_out_rate )) + 
  geom_point(color='blue') +
  geom_line(color='red',data = emp_data, aes(x=sqrt(Salary_hike), y=pred))
confint(emp_data_model,level=0.95)
emp_data_dataset <- as.data.frame(predict(emp_data_model,interval='predict'))
emp_data_final <- cbind(emp_data,emp_data_dataset)
write.csv(emp_data_final,file='emp_data_x_squared')
#Model 3(with Square root transformation on both the Variables)
library(ggplot2)
library(readr)
emp_data <- read.csv('E:/excelr data/assignments/simple regression/emp_data.csv')
View(emp_data)
attach(emp_data)
cor(sqrt(Salary_hike),sqrt(Churn_out_rate))
emp_data_model <- lm(sqrt(Churn_out_rate)~sqrt(Salary_hike))
summary(emp_data_model)
pred <- predict(emp_data_model)
ggplot(data = emp_data, aes(x = sqrt(Salary_hike), y = sqrt(Churn_out_rate))) + 
  geom_point(color='blue') +
  geom_line(color='red',data = emp_data, aes(x=sqrt(Salary_hike), y=pred))
confint(emp_data_model,level=0.95)
emp_data_dataset <- as.data.frame(predict(emp_data_model,interval='predict'))
emp_data_final <- cbind(emp_data,emp_data_dataset)
write.csv(emp_data_final,file='emp_data_comp.transformed')
