#install.packages("janitor")
#install.packages("lubridate")
#install.packages('tidyr')
#install.packages('imputeTS')
library(readr)
library(readxl)
library(janitor)
library(lubridate)
library(tidyr)
library(tseries)
library(imputeTS)
delhi <- read.csv("C:/Users/Arjun/Desktop/Delhi (2).csv",2)
class(delhi$date_time)
class(delhi$pm25)
#delhi$pm25 <- as.numeric(delhi$pm25,na.action='na.pass')
#delhi$date <- as.POSIXct(as.character(delhi$date),format="%m/%d/%Y %H:%M:%S")
hist(delhi$pm25)
boxplot(delhi$pm25)
sum(is.na(delhi$pm25))
#creating time_series
new <- ts(delhi$pm25,frequency = 24)
plot(new)
class(new,main="original")
# imputing NA values using linear interpolation
new2 <- na.interpolation(new)
plot(new2,main="linear interploation")
# imputing NA values using seasonality adjustment+ linear interploation
new3 <- na.seadec(new,algorithm = 'interpolation')
plot(new3,main="seasonality adjustment+ linear interploation")
# imputing NA values randomly
new4 <- na.random(new)
plot(new4,main="random imputation")
# imputing NA values using Last Obs. Carried Forward
new5 <- na.locf(new,option = "locf")
plot(new5,main="Last Obs. Carried Forward")
#imputing NA values using Next Obs. Carried Backward
new6 <- na.locf(new,option='nocb')
plot(new6,main="Next Obs. Carried Backward")
# finding the structure
str(new)
str(new2)
str(new3)
str(new4)
str(new5)
str(new6)
# plotting boxplot
boxplot(new~cycle(new),main='original')
boxplot(new~cycle(new2),main='linear interpolation')
boxplot(new~cycle(new3),main='seasonal adjustment and linear interpolation')
boxplot(new~cycle(new4),main='random imputation')
boxplot(new~cycle(new5),main='Last Obs. Carried Forward')
boxplot(new~cycle(new6),main='Next Obs. Carried Backward')
#Summary
summary(new)
summary(new2)
summary(new3)
summary(new4)
summary(new5)
summary(new6)
