library(readxl)
airlines <- read_excel("E:/excelr data/assignments/clustering/EastWestAirlines.xlsx",1)
View(airlines)
norm_airlines <- as.data.frame(scale(airlines[,-1]))
View(norm_airlines)
wss = (nrow(norm_airlines)-1)*sum(apply(norm_airlines, 2, var))		 
for (i in 2:20) wss[i] = sum(kmeans(norm_airlines, centers=i)$withinss)
plot(1:20, wss, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
title(sub = "K-Means Clustering Scree-Plot")
install.packages("kselection")
library(kselection)
k <- kmeans(norm_airlines,10)
install.packages("animation")
library(animation)
k <- kmeans.ani(norm_airlines,10)
k$centers
final <- data.frame(norm_airlines,k$cluster)
View(final)
aggregate(airlines[,3:11], by=list(k$cluster), FUN=mean)
