#MODEL 1 (without applying transformation)
library(ggplot2)
library(readr)
diet <- read.csv('E:/excelr data/assignments/simple regression/calories_consumed.csv')
View(diet)
attach(diet)
plot(Weight.gained..grams.,Calories.Consumed)
cor(Weight.gained..grams.,Calories.Consumed)
diet_model <- lm(Calories.Consumed~Weight.gained..grams.)
summary(diet_model)
pred1 <- predict(diet_model)
ggplot(data = diet, aes(x = Weight.gained..grams., y = Calories.Consumed)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = diet, aes(x=Weight.gained..grams., y=pred1))
confint(diet_model,level=0.95)
diet_dataset <- predict(diet_model,interval='predict')
diet_dataset <- as.data.frame(diet_dataset)
diet_final <- cbind(diet,diet_dataset)

setwd("E:/excelr data/assignments/simple regression")
write.csv(diet_final,file='diet_final')
#MODEL 2 (with applying transformation to the independent variable)
library(ggplot2)
library(readr)
diet <- read.csv('E:/excelr data/assignments/simple regression/calories_consumed.csv')
View(diet)
attach(diet)
plot(Weight.gained..grams.,Calories.Consumed)
cor(Weight.gained..grams.,Calories.Consumed)
diet_model <- lm(Calories.Consumed~log(Weight.gained..grams.))
summary(diet_model)
pred1 <- predict(diet_model)
ggplot(data = diet, aes(x =log(Weight.gained..grams.), y = Calories.Consumed)) + 
  geom_point(color='blue') +
  geom_line(color='red',data = diet, aes(x=log(Weight.gained..grams.), y=pred1))
confint(diet_model,level=0.95)
diet_dataset <- predict(diet_model,interval='predict')
diet_dataset <- as.data.frame(diet_dataset)
diet_final <- cbind(diet,diet_dataset)

setwd("E:/excelr data/assignments/simple regression/diet_fit")
write.csv(diet_final,file='diet_final_logged')
#MODEL 2 ( applying transformation to the dependent variable)
library(ggplot2)
library(readr)
diet <- read.csv('E:/excelr data/assignments/simple regression/calories_consumed.csv')
View(diet)
attach(diet)
plot(Weight.gained..grams.,Calories.Consumed)
cor(Weight.gained..grams.,Calories.Consumed)
diet_model <- lm(log(Calories.Consumed)~Weight.gained..grams.)
summary(diet_model)
pred1 <- predict(diet_model)
ggplot(data = diet, aes(x = Weight.gained..grams., y = log(Calories.Consumed))) + 
  geom_point(color='blue') +
  geom_line(color='red',data = diet, aes(x=Weight.gained..grams., y=pred1))
confint(diet_model,level=0.95)
diet_dataset <- predict(diet_model,interval='predict')
diet_dataset <- as.data.frame(diet_dataset)
diet_final <- cbind(diet,diet_dataset)

setwd("E:/excelr data/assignments/simple regression/diet_fit")
write.csv(diet_final,file='diet_final_looged_y')
